version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    working_dir: "/var/www/html"
    depends_on:
      - db

  db:
    image: mysql:8.0.39-debian
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=profiles_db
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql

volumes:
    db_data:
